INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Middleware', 1, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Plattform', 2, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Datenbank', 3, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Entwurfswerkzeug', 4, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Entwicklungswerkzeug', 5, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Programmiersprache', 6, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Sprache', 7, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Versionskontrolle', 8, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Framework', 9, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Bibliothek', 10, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Testwerkzeug', 11, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Build-Werkzeug', 12, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Auszeichnungssprache', 13, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Skripting', 14, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Framework Web UI', 15, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Framework UI', 16, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Framework Kommunikation', 17, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Projektmanagement', 18, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Design-Methode', 19, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Systemanalyse', 20, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Logging', 21, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Visualisierung', 22, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Business Process Modelling', 23, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Architekturmodell', 24, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Datenmigration', 25, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Azure', 26, 0);
INSERT INTO t_category (cat_name, cat_id, cat_deleted) VALUES ('Messaging', 27, 0);
