INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (1, 'Subversion', 8, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (2, 'Git', 8, '1.7', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (3, 'Maven', 12, '3', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (4, 'Maven', 12, '2', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (5, 'Eclipse', 5, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (6, 'Apache', 1, '2.4', 1);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (7, 'Tomcat', 1, '7', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (8, 'Tomcat', 1, '6', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (9, 'Java', 6, '8', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (10, 'Java', 6, '7', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (11, 'Java', 6, '6', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (12, 'Java', 6, '1.5', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (13, 'Java', 6, '1.4', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (14, 'Java', 6, '1.3', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (15, 'JBoss', 1, '6', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (16, 'JBoss', 1, '5', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (17, 'PostgreSQL', 3, '11', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (18, 'PostgreSQL', 3, '10', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (19, 'PostgreSQL', 3, '9', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (20, 'PostgreSQL', 3, '8', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (21, 'MySQL', 3, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (22, 'SQLite', 3, '3.x', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (23, 'Oracle', 3, '11', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (24, 'Oracle', 3, '10', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (25, 'Oracle', 3, '9', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (26, 'Oracle', 3, '8', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (27, 'Perl', 14, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (28, 'Bash', 14, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (29, 'PHP', 6, '7', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (30, 'PHP', 6, '5', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (31, 'Apache FOP', 10, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (32, 'AngularJS', 15, '1.6', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (33, 'Javascript', 14, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (34, 'HTML', 13, '5', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (35, 'HTML', 13, '4', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (36, 'Swing', 16, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (37, 'OrientDB', 3, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (38, 'MongoDB', 3, '3.6', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (39, 'JSP', 15, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (40, 'Spring Security', 9, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (41, 'Spring Data REST', 9, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (42, 'Spring Data', 9, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (43, 'Spring Boot', 9, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (44, 'JSF', 15, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (45, 'Servlet', 9, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (46, 'ANTLR', 5, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (47, 'Visual Paradigm', 4, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (48, 'Sparx Enterprise Architect', 4, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (49, 'Rational Rose', 4, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (50, 'Telelogic CM Synergy', 8, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (51, 'Netflix Stack', 9, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (52, 'Protobuf', 17, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (53, 'JAX-WS', 17, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (54, 'JMeter', 11, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (55, 'Mercurial Testrunner', 11, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (56, 'Webdriver', 11, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (57, 'Newman', 11, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (58, 'Postman', 11, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (59, 'Selenium', 11, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (60, 'JUnit', 11, '5', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (61, 'JUnit', 11, '4', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (62, 'JUnit', 11, '3', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (63, 'SOAP-UI', 11, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (64, 'Oracle Forms', 15, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (65, 'Bootstrap', 15, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (66, 'Ant', 12, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (67, 'Docbook', 13, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (68, 'Hebräisch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (69, 'Persisch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (70, 'Türkisch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (71, 'Griechisch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (72, 'Japanisch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (73, 'Dänisch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (74, 'Polnisch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (75, 'Italienisch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (76, 'Russisch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (77, 'Chinesisch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (78, 'Spanisch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (79, 'Französisch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (80, 'Deutsch', 7, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (81, 'Clean Code', 19, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (82, 'Xtreme Programming', 19, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (83, 'Domänen-getriebene Entwicklung', 19, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (84, 'testgetriebene Entwicklung', 19, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (85, 'Kanban', 18, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (86, 'Wasserfall', 18, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (87, 'SCRUM', 18, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (88, 'V-Modell XT', 18, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (89, 'ELK-Stack', 20, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (90, 'Elasticsearch', 21, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (91, 'Logstash', 21, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (92, 'Kibana', 22, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (93, 'Nagios', 20, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (94, 'Activity', 23, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (95, 'Flowable', 23, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (96, 'WebLogic', 1, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (97, 'Gradle', 12, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (98, 'Model-Driven-Design', 19, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (99, 'Service-orientierte Architektur', 24, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (100, 'Enterprise Service Bus', 1, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (101, 'Feign Clients', 17, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (102, 'Flyway', 25, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (103, 'Glassfish', 1, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (104, 'Wildfly', 1, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (105, 'Undertow', 1, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (106, 'Resource Templates', 26, '', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (107, 'Java', 6, '11', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (108, 'Table Storage', 26, '', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (109, 'CosmosDB', 26, '', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (110, 'Service Bus', 26, '', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (111, 'EventHub', 26, '', 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (112, 'Microservice', 24, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (113, 'RabbitMQ', 27, NULL, 0);
INSERT INTO t_capability (cap_id, cap_name, cap_category_id, cap_version, cap_deleted) VALUES (114, 'MQTT', 27, NULL, 0);
